import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/colors.css";
import ThemeProvider from "@/components/theme/theme-provider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  mac,
  iphone,
}: Readonly<{
  mac: React.ReactNode;
  iphone: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className={cn("hidden md:block")}>
            <main>{mac}</main>
          </div>
          <div className={cn("md:hidden")}>
            <main>{iphone}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
